import os

VERSION = "0.0.1"

# time format of pendulum
DATETIME_FORMAT = "DD MMMM YYYY HH:mm:ss A"
DATE_FORMAT = "DD MMMM YYYY"

DATETIME_FORMAT_MOMENT = "YYYY-MM-DD HH:mm:ss"
DATE_FORMAT_MOMENT = "YYYY-MM-DD"
